apiVersion: 1

datasourcees: 
- name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    jsonData: {}

# Optional: a second CSV-specific datasource (you can skip if using Infinity only)
- name: CSV (marcusolsson)
  type: marcusolsson-csv-datasource
  access: proxy
  jsonData:
    storage: url