apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: wineshop
spec:
  replicas: 2  # 2 replicas pour haute disponibilité
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: gcr.io/PROJECT_ID/wineshop-api:latest  # À remplacer avec votre projet GCP
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: DATABASE_URL
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: REDIS_PORT
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: MINIO_ENDPOINT
        - name: MINIO_PORT
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: MINIO_PORT
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: wineshop-secrets
              key: minio-root-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wineshop-secrets
              key: minio-root-password
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: wineshop-config
              key: NODE_ENV
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: wineshop
spec:
  selector:
    app: api
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
