apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wineshop
spec:
  replicas: 2  # 2 replicas pour haute disponibilité
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/emmaloou/winederful/frontend:latest  # Image depuis GitHub Container Registry
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://api-service:4000"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: wineshop-secrets
              key: nextauth-secret
        - name: NEXTAUTH_URL
          value: "https://wineshop.VOTRE-DOMAINE.com"  # À remplacer
        - name: HOSTNAME
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wineshop
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer  # Expose le frontend avec une IP publique
